# Generated by Django 6.0.3 on 2026-03-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger', models.CharField(max_length=100)),
                ('bill_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('code', models.CharField(max_length=50)),
                ('item_code', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('rate', models.FloatField()),
                ('discount', models.FloatField()),
                ('description', models.TextField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
