# Generated by Django 6.0.3 on 2026-03-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierRef', models.CharField(max_length=100)),
                ('dispatchDocNo', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=200)),
                ('creditDays', models.IntegerField()),
                ('dispatchThrough', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('termsType', models.CharField(max_length=100)),
                ('terms', models.TextField()),
                ('taxable', models.FloatField()),
                ('tax', models.FloatField()),
                ('net', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
