# Generated by Django 6.0.3 on 2026-03-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_dispatchsummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatchsummary",
            name="currencyAmountLabel",
            field=models.CharField(default="Rupees", max_length=50),
        ),
        migrations.AddField(
            model_name="dispatchsummary",
            name="currencyCode",
            field=models.CharField(default="INR", max_length=10),
        ),
        migrations.AddField(
            model_name="dispatchsummary",
            name="currencyName",
            field=models.CharField(default="India", max_length=100),
        ),
        migrations.AddField(
            model_name="dispatchsummary",
            name="currencyRateToInr",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="dispatchsummary",
            name="currencySymbol",
            field=models.CharField(default="\u20b9", max_length=10),
        ),
        migrations.AddField(
            model_name="dispatchsummary",
            name="discount",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="dispatchsummary",
            name="roundoff",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="dispatchsummary",
            name="subtotal",
            field=models.FloatField(default=0),
        ),
    ]
