# Generated by Django 6.0.3 on 2026-03-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_dispatchsummary_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCode', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('mrp', models.FloatField(blank=True, null=True)),
                ('itemType', models.CharField(blank=True, max_length=100)),
                ('hsnCode', models.CharField(blank=True, max_length=50)),
                ('purchasePrice', models.FloatField(blank=True, null=True)),
                ('itemName', models.CharField(blank=True, max_length=100)),
                ('tax', models.CharField(blank=True, max_length=20)),
                ('salesPrice', models.FloatField(blank=True, null=True)),
                ('categoryName', models.CharField(blank=True, max_length=100)),
                ('partNo', models.CharField(blank=True, max_length=50)),
                ('minimumOrderQty', models.IntegerField(blank=True, null=True)),
                ('itemGroup', models.CharField(blank=True, max_length=100)),
                ('batchNo', models.CharField(blank=True, max_length=50)),
                ('minimumStockQty', models.IntegerField(blank=True, null=True)),
                ('itemDescription', models.TextField(blank=True, max_length=250)),
                ('isStock', models.BooleanField(default=False)),
                ('needQc', models.BooleanField(default=False)),
                ('needWarranty', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('needService', models.BooleanField(default=False)),
                ('needSerialNo', models.BooleanField(default=False)),
                ('itemImage', models.FileField(blank=True, null=True, upload_to='itemfolder/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
